### ISSUE TITLE
How could I make it work wiht qtarget ???

### ISSUE THREAD

**Issue by Jostekkk** [Giana/g-drugselling#8]
I have qtarget and ox_invenotry and all scripts except yours work how could i fix it

**Comment by Giana** [comment]
G-DrugSelling uses qb-inventory and qb-target, so it not working in your server is expected as you are not using two of its dependencies. You would have to change the references to qb-inventory and qb-target in the code to use the scripts that you are using instead of those. You can refer to their documentation but I believe ox_inventory isn't very compatible with the QB framework to begin with so I imagine this might be a difficult project.
